spring:
  application:
    name: gateway-web
  cloud:
      gateway:
        globalcors: #全局配置
          cors-configurations:
            '[/**]': # 匹配所有请求
                allowedOrigins: "*" #跨域处理 允许所有的域
                allowedMethods: # 支持的方法
                  - GET
                  - POST
                  - PUT
                  - DELETE
        routes:
              - id: changgou_goods_route
                #uri: http://localhost:18081
                #lb负载均衡，使用服务名负载均衡
                uri: lb://goods
                predicates:
                        #用户请求域名配置，所有以一下域名的请求都被   http://localhost:18081  处理
                        #- Host=cloud.itheima.com**
                        #所有以/brand开始的请求都交给  http://localhost:18081 处理
                 - Path=/**
                 filters:
                  #- PrefixPath=/brand
                  - StripPrefix=1
                  - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
                    args:
                      key-resolver: "#{@ipKeyResolver}"
                      redis-rate-limiter.replenishRate: 1
                      redis-rate-limiter.burstCapacity: 1

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true